openapi: 3.0.0
info:
  title: testbed
  version: 0.0.1
paths:
  /:
    post:
      requestBody:
        description: desc
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestObject'
      responses:
        '200':
          description: desc
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseObject'
            application/xml:
              schema:
                $ref: '#/components/schemas/responseObject'
components:
  schemas:
    responseObject:
      type: object
      properties:
        baz:
          type: string
    requestObject:
      allOf:
        - $ref: '#/components/schemas/baseObject'
        - $ref: '#/components/schemas/childObject'
      discriminator:
        propertyName: $
    baseObject:
      type: object
      required:
        - $ 
      properties:
        $:
          type: string
        foo:
          type: string
    childObject:
      type: object
      properties:
        bar:
          type: string
