openapi: 3.0.0
info:
  title: testbed
  version: 0.0.1
paths:
  /:
    get:
      requestBody:
        description: desc
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestObject'
      responses:
        '200':
          description: desc
components:
  schemas:
    requestObject:
      allOf:
        - $ref: '#/components/schemas/baseObject'
        - $ref: '#/components/schemas/childObject'
      discriminator:
        propertyName: objType
    baseObject:
      type: object
      required:
        - objType
      properties:
        objType:
          type: string
        foo:
          type: string
    childObject:
      type: object
      properties:
        bar:
          type: string
